### ISSUE TITLE
Pass through a conf volume?

### ISSUE THREAD

**Issue by aethant** [CliffordAnderson/docker-containers#1]
Hi, 

I'm trying to create a conf volume to pass through my own neo4j.conf file. However, it seems to cause conflicting instances to run at once.

For example, if i do the following in my compose file:

```
graphdb:
      container_name: mygraphdb
      image: andersoncliffb/neo4j-with-apoc-and-spatial
      networks:
        - back
      volumes:
        - $HOME/neo4j/myapp/conf:/conf
        - $HOME/neo4j/myapp/logs:/logs
        - $HOME/neo4j/myapp/data:/data
      ports:
        - "7474:7474"
        - "7687:7687"   
      expose:
        - "7474"
        - "7687"
```

I see the following at startup:

```
mygraphdb | 2017-02-22 22:18:39.798+0000 INFO  Starting...
mygraphdb | 2017-02-22 22:18:40.545+0000 INFO  Bolt enabled on localhost:7687.
mygraphdb | 2017-02-22 22:18:40.545+0000 INFO  Bolt enabled on localhost:7687.
mygraphdb | 2017-02-22 22:18:40.545+0000 INFO  Bolt enabled on localhost:7687.
```

and then an error 3x:

`ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@113bde5b' was successfully initialized, but failed to start. Please see attached cause exception.` 

My ultimate end goal is to increase the heap size, so if there's an easier way than pointing to a conf file, i'm open to that, but really I'd like to resolve both issues, as being able to control the configuration would be fairly important.
